[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@selfxyz/contracts-v2/=lib/self-contracts-v2/",
    "forge-std/=lib/forge-std/src/"
]

# Celo network configurations
[rpc_endpoints]
celo_testnet = "https://alfajores-forno.celo-testnet.org"
celo_mainnet = "https://forno.celo.org"

[etherscan]
celo_testnet = { key = "${CELOSCAN_API_KEY}", url = "https://api-alfajores.celoscan.io/api" }
celo_mainnet = { key = "${CELOSCAN_API_KEY}", url = "https://api.celoscan.io/api" }

# Compiler settings
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = false

# Testing
verbosity = 2
ffi = false
fs_permissions = [{ access = "read-write", path = "./" }]