[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = false
verbosity = 2
ffi = false

remappings = [
      "forge-std/=lib/forge-std/src/"
     "@selfxyz/=node_modules/@selfxyz/"
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

# Celo network configurations
[rpc_endpoints]
celo_testnet = "https://alfajores-forno.celo-testnet.org"
celo_mainnet = "https://forno.celo.org"
